### ISSUE TITLE
Simple file reader to make lexer easy

### ISSUE THREAD

**Issue by ghost** [JLWalsh/StackVM#16]
# Idea

You should implement a simple file reader. Assign each opcode a byte, then open a file in your favorite binary editor and write some code.

# Detail

 You could have a FileReader class that looks through the file (fopen, fseek, you know the drill) and if there is an opcode it adds that, and if there are parameters it uses the bytes afterwards to make them. Finally you can make a lexer that simple takes a string and separates it by spaces. The strings would be mapped to bytes and written to a file, which your new file reader can execute.

**Comment by JLWalsh** [comment]
First of all, thank you for the idea! I really appreciate you taking the time to write this :)

So if I understand correctly, your idea would be to make the VM open up a file, read the bytecode, and execute it? In that case, most of the hard work would already be done, as the VM can already read bytecode, all it needs is a simple method to load the bytecode from a file!

Basically, your idea would be to add a file reader to the VM, so that it may read bytecode other than the one hardcoded in the program. Then, write a small parser which takes a string and splits each instruction & parameter by spaces, which I assume generates the bytecode that the VM will read. If that is your idea, I was planning on doing so (see [executable.h](https://github.com/JLWalsh/StackVM/blob/master/src/vm/executable.h)), but I decided to wait until I had implemented objects. I'll be honest, I don't really plan on continuing this project, as I decided to rewrite a [new object-oriented VM from scratch](https://github.com/JLWalsh/ObjectVM).
